config/routes.rb
Rails.application.routes.draw do
  get 'likes/new'
  get 'likes/create'
  get 'likes/destroy'
  resources :sessions, only: [:create]
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  
  resources :users, except: [:index] do
    resources :articles, only: [:new, :create, :edit, :update]
    # member do
    #   get :articles
    # end
  end
  
  resources :articles, only: [:index, :destroy, :show] do
    collection do
      get :recent
      get :top
      get :my
    end

    resources :likes, only: [:create]
  end
  resources :likes, only: [:destroy]
  
  root 'articles#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes

  def days_ago
    time = (Time.current - created_at) / (60 * 60)
    return_string = "#{time.round} #{time > 1 ? 'hours' : 'hour'}"
    if time >= 24
      days = (time / 24).round
      hours = (time % 24).round
      return_string = "#{days} #{days > 1 ? 'days' : 'day'} #{hours} #{hours > 1 ? 'hours' : 'hour'}"
    end
    "#{return_string} ago"
  end

  def liked?(current_user)
    # raise
    (users.include? current_user)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article
  validates :user, presence: true
  validates :article, presence: true
  validates :user, uniqueness: { scope: :article }
  # should have unique combination of user and article for each like
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_secure_password

  validates :email, presence: true, uniqueness: true, format: {
    with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  }
  validates :user_name, presence: true, uniqueness: true

  def to_param
    user_name
  end

  def username
    "@#{user_name}"
  end

  def no_of_articles
    articles.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # skip_before_action :verify_authenticity_token
  
  private
  
  def current_user
    User.where(id: session[:user_id]).first
  end

  # def redirect_app(initial_url, exception_url)
  #   unless request.referer == initial_url
  #     redirect_to request.referer
  #   else
  #     redirect_to exception_url
  #   end
  # end

  def same_user
    @user = User.find_by_user_name(params[:id])
    unless @user
      @user = Article.find(params[:id]).user
    end
    current_user == @user
  end

  def find_like(article)
    Like.where(user: current_user).where(article: article).first
  end

  helper_method :current_user, :same_user, :find_like
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # skip_before_action :login_required, :only => [:index, :show]
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :find_user, only: [:new, :create, :edit, :update] # , :user_article

  def index
    @articles = Article.all
  end
  
  def show
  end

  def recent
    @articles = Article.all.sort_by &:created_at
  end

  def top
    redirect_to articles_path
  end

  def my
    @articles = current_user.articles
  end

  def new
    if current_user && current_user == @user
      @user = current_user
      @article = Article.new
    else
      # render login with email of user[params[:id]]
      render 'sessions/new', notice: 'Log in to create a article'
    end
  end
  
  def create
    article = Article.new(build_article)
    article.user = @user
    if article.save
      redirect_to articles_path
    else
      render :new
    end
  end
  
  def edit
    unless hard_checker
      reset_session
      # raise
      flash[:notice] = 'I see what you are trying to do.Next time, I will call cops on you.Login to save yourself.'
      render 'sessions/new'
    end
  end
      
  
  def update
    if hard_checker
      @article.update(build_article)
    end
    # raise
    redirect_to article_path(@article)
  end
  
  def destroy
    user = User.find(@article[:user_id])
    @article.destroy
    redirect_to user_path(user.to_param)
  end

  private

  def build_article
    params.require(:article).permit(:title, :content)
  end

  def find_article
    @article = Article.find(params[:id])
  end

  def find_user
    @user = User.find_by_user_name(params[:user_id])
  end

  def hard_checker
    @article.user == @user && current_user == @user
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    if current_user
      @user = current_user
      @article = Article.find(params[:article_id])
      like = Like.create(user: @user, article: @article)
    end
    redirect_to request.referer
    # raise
  end

  def destroy
    like = Like.find(params[:id])
    if current_user == like.user
      like.destroy
    end
    redirect_to request.referer
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    # raise
    if current_user
      redirect_to user_path(current_user)
    end
  end

  def create
    @user = User.find_by_email(params[:user][:email]).try(:authenticate, params[:user][:password])
    if @user
      session[:user_id] = @user.id
      # redirect_to root_url, notice: 'Logged in!'
      # irequest.referer == root_url
      unless request.referer == login_url
        redirect_to request.referer
      else
        redirect_to user_path(@user.to_param)
      end
    else
      # render :new # It makes 2 request to change to GET request
      redirect_to login_path
    end
    # raise
  end

  def destroy
    reset_session
    redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    unless current_user
      render 'sessions/new'
    end
  end
  
  # GET /users/new
  def new
    if current_user
      redirect_to user_path(current_user.to_param)
    end
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      session[:logged_in] = true
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by_user_name(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_articles.html.erb
<div class="list-group mt-5">
  <% articles.each do |article| %>
    <div class="list-group-item list-group-item-action border shadow-sm p-3 my-2 bg-white">
      <div class="d-flex w-100 justify-content-between">
        <h5 class="mb-1"><%= link_to article.title, article_path(article), class: "article-title" %></h5>
        <small><%= article.days_ago %></small>
      </div>
      <small><%=link_to article.user.username, user_path(article.user.to_param) %></small>
      <div class="d-flex w-100 justify-content-between">
        <p class="mb-1"><%= article.content[0..20]%></p>
        <small>
          <%= render 'like', article: article %>
        </small>
      </div>
    </div>
  <% end %>
</div>


<%# if current_user && article.user != current_user && !(article.users.include? current_user) %>
  <%#= link_to "like", article_likes_path(article), method: :POST %>
<%# elsif (article.users.include? current_user)  && article.user != current_user %>
  <%## <%#= raise %>
  <%#= link_to "like", like_path(find_like(article)), method: :delete %>
<%# else %>
  <%#= "like"  %>      
<%# end %>

app/views/articles/_form.html.erb
<%= simple_form_for(article) do |f| %>
  <%= f.input :title %>
  <%= f.input :content %>
  <%= f.submit class: "btn btn-success" %>
<% end %>

app/views/articles/_index.html.erb
<h4 class="text-center mt-5">Articles</h4>
<%= render 'nav' %>
<%= render 'articles', articles: articles %>

app/views/articles/_like.html.erb
<%= article.likes.count %>
<% if  current_user &&  article.user != current_user %>
  <% if article.liked?(current_user) %>
    <%= link_to '<i class="fas fa-thumbs-up"></i>'.html_safe, like_path(find_like(article)), method: :delete %>
  <% else %>
    <%= link_to '<i class="far fa-thumbs-up"></i>'.html_safe, article_likes_path(article), method: :POST %>
  <% end %>
<% else %>
  <i class="far fa-thumbs-up"></i>
<% end %>

app/views/articles/_nav.html.erb
<ul class="list-group list-group-horizontal-md">
  <li class="list-group-item"><%= link_to "Recent", recent_articles_path %></li>
  <li class="list-group-item"><%= link_to "Top", articles_path %></li>
  <!--<% if current_user %>
    <li class="list-group-item"><%= link_to "My Article", my_articles_path %></li>
  <% end %>-->
</ul>

app/views/articles/edit.html.erb
<%= render 'form', article: [@user, @article] %>

app/views/articles/index.html.erb
<% @articles.each do |article| %>
  <!--<div class="card my-3 border-0">
    <div class="card-body">
      <h3 class="inline-block card-title border-bottom py-2"><%= link_to article.title, article_path(article), class: "article-title" %></h3>
      <p class="card-text"><%= article.content %></p>
    </div>
  </div>-->

  <div class="card my-3">
    <div class="card-body p-2">
      <h6 class="card-title"><%= link_to article.title, article_path(article), class: "article-title" %></h6>
      <p class="card-text">By. <%=link_to "@#{article.user.to_param}", user_path(article.user.to_param) %></p>

      <p class="card-text"><%= article.content[0..20] %></p>
      <!--<a href="#" class="btn btn-primary">Go somewhere</a> -->
    </div>
  </div>
  
<% end %>

app/views/articles/my.html.erb
<%= render 'index', articles: @articles %>

app/views/articles/new.html.erb
<div class="list-group-item shadow-sm p-3 mt-2 mb-5 bg-white">
  <h4>Notice</h4>
  <p>You can write content similar to how you write html.</p>
  <p>p.s Please use <strong> 🦾</strong> inside paragraph.</p>
</div>

<%= render 'form', article: [@user, @article] %>

app/views/articles/recent.html.erb
<%= render 'index', articles: @articles %>

app/views/articles/show.html.erb
<div class="card my-3 border-0">
  <div class="card-body">
    <h3 class="inline-block card-title border-bottom py-2">
      <%= @article.title %>
      <% if same_user %>
        <small><%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_user_article_path(current_user, @article) %></small>
        <small><%= link_to '<i class="fas fa-trash"></i>'.html_safe, article_path(@article), method: "delete", data: { confirm: "Do you want to delete this article?" } %></small>  
      <% end %>
    </h3>
    <p class="card-text"><%= simple_format((@article.content)) %></p>
  </div>
</div>

app/views/articles/top.html.erb
<%= render 'index', articles: @articles %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionTrail</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="user_header">
      <div class="navbar navbar-light bg-light justify-content-between px-5">
        <%= link_to '<h3 class="inline-block">Newspaper</h3>'.html_safe, articles_path, class:"navbar-brand" %>
        <% if current_user %> 
          <div class="link-box">
            <%= link_to "@#{current_user.to_param}", user_path(current_user), class: "login" %>
            <%= link_to "create a post", new_user_article_path(current_user), class: "btn btn-info" %>
            <%= link_to "Log Out", logout_path, class: "btn border border-primary login" %>  
          </div>
        <% else %>
          <div class="link-box">
            <%= link_to "Sign Up", signup_path, class: "btn btn-primary" %>  
            <%= link_to "Log In", login_path, class: "btn border border-primary login" %>  
          </div>
        <% end %>  
      </div> 
    </div>  
    <!-- <% flash.each do |key, value| %>  
      <%= content_tag(:div, class: "alert alert-#{key}") do %>  
        <p><%= value %></p>  
      <% end %>
    <% end %>  -->
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for(user) do |f| %>
  <%= f.input :user_name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class= "list-group-item shadow p-3 mb-5 bg-white rounded">
  <p>
    <strong>UserName:</strong>
    <%= @user.username %>
  </p>
  <p class="mb-0">
    <strong>Total posts:</strong>
    <%= @user.no_of_articles %>
  </p>
</div>
<h3>Articles</h3>
<ul class="list-group">
  <% @user.articles.each do |article| %>
    <li class="list-group-item d-flex justify-content-between border h6 shadow-sm p-3 my-2 bg-white"><%= link_to article.title, article_path(article) %>
    <% if same_user %>
      <div class="user-link-box">
        <%= link_to '<i class="fas fa-edit"></i>'.html_safe, edit_user_article_path(current_user, article) %>
        <%= link_to '<i class="fas fa-trash"></i>'.html_safe, article_path(article), method: "delete", data: { confirm: "Do you want to delete this article?" } %>   
      </div>
    <% end %>
    </li>
  <% end %>
</ul>